server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xiaomi?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    password: 123456
    url: 127.0.0.1
    port: 6379
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: bmi-producer
  consumer:
    group: bmi-consumer


mybatis-plus:
  mapper-locations: classpath:mappers/*.xml